BROADCAST_CONNECTION=reverb
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

REVERB_APP_ID1=410853
REVERB_APP_KEY1=c3ot369vmc6dmbsz2oea
REVERB_APP_SECRET1=cbo2oygiavf1rvgnwdii
REVERB_HOST1=127.0.0.1
REVERB_PORT1=8080
REVERB_SCHEME1=http

VITE_REVERB_APP_KEY1="${REVERB_APP_KEY}"
VITE_REVERB_HOST1="${REVERB_HOST}"
VITE_REVERB_PORT1="${REVERB_PORT}"
VITE_REVERB_SCHEME1="${REVERB_SCHEME}"
VITE_APP_NAME1="${APP_NAME}"